#:import Factory kivy.factory.Factory

<SpinnerOptions>:

<FontGenerator>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        size_hint_y: None
        height: "50dp"
        Button:
            id: btn
            text: "字体生成器"
            color: 0.4, 0.4, 0.4, 1
            background_normal: "Assets/ButtonS_White_Up.png"
            background_down: "Assets/ButtonS_White_Down.png"
            on_parent: dropdown.dismiss()
            on_release: dropdown.open(self)
            size_hint_y: None
            height: "50dp"

        DropDown:
            id: dropdown
            on_select: btn.text = '{}'.format(args[1])
            size_hint_y: None
            height: "50dp"

            Button:
                text: "环生成器"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "RG"
                    dropdown.dismiss()
            Button:
                text: "方向调整"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "OR"
                    dropdown.dismiss()
            Button:
                text: "部件对齐器"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "PA"
                    dropdown.dismiss()
            Button:
                text: "图像转换器"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "IC"
                    dropdown.dismiss()

    GridLayout:
        cols: 2
        Label:
            text: "字体:"
            color: .35, .35, .35, 1
        GeneralSpinner:
            id: FG_S
            path_index: 1
            background_normal: "Assets/Button_Gray_Up.png"
            background_down: "Assets/Button_Gray_Down.png"
            option_cls: Factory.get("MySpinnerOption")
            on_release: self.update_spinner()
            on_press: self.update_spinner()
        Label:
            text: "文本:"
            color: .35, .35, .35, 1
        TextInput:
            id: FG_Text
            multiline: False
            write_tab: False
            font_size: "20sp"
            padding: [10, self.height/2.2 - self.font_size/2, 10, 10]
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"
            on_touch_down: self.background_normal = "Assets/Normal_Button_Down.png"
        Label:
            text: "间距增加:"
            color: .35, .35, .35, 1
        TextInput:
            id: FG_HS
            multiline: False
            write_tab: False
            font_size: "20sp"
            text: "0"
            padding: [10, self.height/2.2 - self.font_size/2, 10, 10]
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"
        Label:
            text: "颜色纹理:"
            color: .35, .35, .35, 1
        Spinner:
            id: FG_Color_Tex
            text: "Color_White"
            values: "Array", "Color_White", "Color_Orange", "Gold_Foil", "Color_Gray", "Color_Black", "Metal", "Metal_2", "Metal_3", "Metal_4", "Strut_Gray", "Pattern_Squares", "Pattern_Cone", "Pattern_Bars", "Pattern_Bars_Band", "Pattern_Bars_Half", "Nozzle_2", "Nozzle_3", "SV_S1_USA", "SV_S1_Flag", "SV_S2", "SV_S3", "USA_Logo"
            background_normal: "Assets/Button_Gray_Up.png"
            background_down: "Assets/Button_Gray_Down.png"
            option_cls: Factory.get("MySpinnerOption")
        Label:
            text: "X坐标:"
            color: .35, .35, .35, 1
        TextInput:
            id: FG_X
            multiline: False
            write_tab: False
            font_size: "20sp"
            text: "9"
            padding: [10, self.height/2.2 - self.font_size/2, 10, 10]
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"
        Label:
            text: "Y坐标:"
            color: .35, .35, .35, 1
        TextInput:
            id: FG_Y
            multiline: False
            write_tab: False
            font_size: "20sp"
            text: "40"
            padding: [10, self.height/2.2 - self.font_size/2, 10, 10]
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"
        Label:
            text: "新蓝图名称:"
            color: .35, .35, .35, 1
        TextInput:
            id: FG_Blueprint_Name
            multiline: False
            write_tab: False
            font_size: "20sp"
            padding: [10, self.height/2.2 - self.font_size/2, 10, 10]
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"

    FloatLayout:
        size_hint: 1, None
        height: "100dp"
        Button:
            id: FG_Gen
            size_hint: .5, .75
            pos_hint: {"center_x": .5, "y": .125}
            text: "生成"
            color: 0.8, 0.8, 0.8, 1
            background_normal: "Assets/Button_Red_Up.png"
            background_down: "Assets/Button_Red_Down.png"
            on_press: root.FG_generate_blueprint()