<WindowManager>:
    RingGeneratorScreen:
    OrientationScreen:
    PartAlignerScreen:
    FontGeneratorScreen:
    ImageConverterScreen:

<RingGeneratorScreen>:
    name: "RG"
    RingGenerator:

<OrientationScreen>:
    name: "OR"
    Orientation:

<PartAlignerScreen>:
    name: "PA"
    PartAligner:

<FontGeneratorScreen>:
    name: "FG"
    FontGenerator:

<ImageConverterScreen>:
    name: "IC"
    ImageConverter: