#:import Factory kivy.factory.Factory

<MySpinnerOption@SpinnerOption>:
    background_normal: "Assets/Button_Gray_Down.png"
    background_down: "Assets/Button_Gray_Up.png"
    height: "40sp"

<RingGenerator>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        size_hint_y: None
        height: "50dp"
        Button:
            id: btn
            text: "环生成器"
            color: 0.4, 0.4, 0.4, 1
            background_normal: "Assets/ButtonS_White_Up.png"
            background_down: "Assets/ButtonS_White_Down.png"
            on_parent: dropdown.dismiss()
            on_release: dropdown.open(self)
            size_hint_y: None
            height: "50dp"

        DropDown:
            id: dropdown
            on_select: btn.text = '{}'.format(args[1])
            size_hint_y: None
            height: "50dp"

            Button:
                text: "方向调整"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "OR"
                    dropdown.dismiss()
            Button:
                text: "部件对齐器"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "PA"
                    dropdown.dismiss()
            Button:
                text: "字体生成器"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "FG"
                    dropdown.dismiss()
            Button:
                text: "图像转换器"
                size_hint_y: None
                height: "50dp"
                color: 0.4, 0.4, 0.4, 1
                background_normal: "Assets/ButtonS_White_Up.png"
                background_down: "Assets/ButtonS_White_Down.png"
                on_release:
                    app.root.current = "IC"
                    dropdown.dismiss()

    GridLayout:
        cols: 2
        BoxLayout
            Label:
                text: "X坐标:"
                color: .35, .35, .35, 1
            TextInput:
                id: RG_X
                text: "9"
                font_size: "20sp"
                padding: [10, self.height/2.2- self.font_size/2, 10, 10]
                write_tab: False
                multiline: False
                background_active: "Assets/Normal_Button_Up.png"
                background_normal: "Assets/Normal_Button_Down.png"
        BoxLayout
            Label:
                text: "Y坐标:"
                color: .35, .35, .35, 1
            TextInput:
                id: RG_Y
                text: "40"
                font_size: "20sp"
                padding: [10, self.height/2.2- self.font_size/2, 10, 10]
                write_tab: False
                multiline: False
                background_active: "Assets/Normal_Button_Up.png"
                background_normal: "Assets/Normal_Button_Down.png"
        Label:
            text: "环直径:"
            color: .35, .35, .35, 1
        TextInput:
            id: RG_Inner_Diameter
            text: "4"
            font_size: "20sp"
            padding: [10, self.height/2.2- self.font_size/2, 10, 10]
            write_tab: False
            multiline: False
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"
        Label:
            id: RG_Segment_Width_Label
            text: "段宽度:"
            color: .35, .35, .35, 1
        TextInput:
            id: RG_Segment_Width
            text: "1"
            font_size: "20sp"
            padding: [10, self.height/2.2- self.font_size/2, 10, 10]
            write_tab: False
            multiline: False
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"
        Label:
            id: RG_Angle_Increments_Label
            text: "角度增量:"
            color: .35, .35, .35, 1
        BoxLayout:
            Label:
                id: RG_Angle_Value
                size_hint: .1, 1
                text: "5°"
                color: .35, .35, .35, 1
            Slider:
                id: RG_Angle_Increments
                value: 5
                step: 1
                min: 1
                max: 120
                cursor_image: "Assets/Cursor.png"
                background_horizontal: "Assets/ButtonS_White_Down.png"
                background_width: "10sp"
                padding: "20sp"
                on_touch_up: root.validate_slider_angle(self)
                on_touch_move: root.validate_slider_angle(self)
        Label:
            text: "部件类型:"
            color: .35, .35, .35, 1
        Spinner:
            id: RG_Part_Type
            text: "Fuel Tank"
            values: "Fuel Tank", "Fairing", "Battery"
            background_normal: "Assets/Button_Gray_Up.png"
            background_down: "Assets/Button_Gray_Down.png"
            option_cls: Factory.get("MySpinnerOption")
        Label:
            text: "颜色纹理:"
            color: .35, .35, .35, 1
        Spinner:
            id: RG_Color_Tex
            text: "Color_White"
            values: "Array", "Color_White", "Color_Orange", "Gold_Foil", "Color_Gray", "Color_Black", "Metal", "Metal_2", "Metal_3", "Metal_4", "Strut_Gray", "Pattern_Squares", "Pattern_Cone", "Pattern_Bars", "Pattern_Bars_Band", "Pattern_Bars_Half", "Nozzle_2", "Nozzle_3", "SV_S1_USA", "SV_S1_Flag", "SV_S2", "SV_S3", "USA_Logo"
            background_normal: "Assets/Button_Gray_Up.png"
            background_down: "Assets/Button_Gray_Down.png"
            option_cls: Factory.get("MySpinnerOption")
        Label:
            text: "形状纹理:"
            color: .35, .35, .35, 1
        Spinner:
            id: RG_Shape_Tex
            text: "Normal"
            values: "Normal", "Flat", "Flat Smooth", "Rivets", "Half Rivets", "Edges", "Flat Faces", "Interstage", "Interstage_Full", "Edges Faces Top", "Edges Faces Bottom", "Edges Smooth", "Nozzle_4", "Strut"
            background_normal: "Assets/Button_Gray_Up.png"
            background_down: "Assets/Button_Gray_Down.png"
            option_cls: Factory.get("MySpinnerOption")
        Label:
            text: "碎片:"
            color: .35, .35, .35, 1
        Spinner:
            id: RG_Fragment
            text: "1"
            values: "1", "", "left", "right"
            background_normal: "Assets/Button_Gray_Up.png"
            background_down: "Assets/Button_Gray_Down.png"
            option_cls: Factory.get("MySpinnerOption")
        Label:
            text: "反转阴影:"
            color: .35, .35, .35, 1
        ToggleButton:
            id: RG_Reverse_Textures
            text: "否"
            background_normal: "Assets/Button_False.png"
            background_down: "Assets/Button_True.png"
            on_press: root.change_tbutton_state(self)
        Label:
            text: "蓝图名称:"
            color: .35, .35, .35, 1
        TextInput:
            id: RG_Blueprint_Name
            multiline: False
            write_tab: False
            font_size: "20sp"
            padding: [10, self.height/2.2- self.font_size/2, 10, 10]
            background_active: "Assets/Normal_Button_Up.png"
            background_normal: "Assets/Normal_Button_Down.png"

    FloatLayout:
        size_hint: 1, None
        height: "100dp"
        Button:
            id: RG_Gen
            size_hint: .5, .75
            pos_hint: {"center_x": .5, "y": .125}
            text: "生成"
            color: 0.8, 0.8, 0.8, 1
            background_normal: "Assets/Button_Red_Up.png"
            background_down: "Assets/Button_Red_Down.png"
            on_press: root.RG_generate_blueprint()